all:
	pdflatex resume.tex
	cp resume.pdf Caleb-Adams-CV.pdf
	pdflatex 2page.tex
	cp 2page.pdf Caleb-Adams-2page-Resume.pdf
cv:
	pdflatex resume.tex
	cp resume.pdf Caleb-Adams-CV.pdf
2page:
	pdflatex 2page.tex
	cp 2page.pdf Caleb-Adams-2page-Resume.pdf
clean:
	rm -f *~
	rm -f *.aux
	rm -f *.log
	# rm -f *.pdf
	rm -f *.out
